// Code generated by go-swagger; DO NOT EDIT.

package health_check

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"gateway/gen/models"
)

// GetHealthCheckReader is a Reader for the GetHealthCheck structure.
type GetHealthCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHealthCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHealthCheckOK creates a GetHealthCheckOK with default headers values
func NewGetHealthCheckOK() *GetHealthCheckOK {
	return &GetHealthCheckOK{}
}

/*
GetHealthCheckOK describes a response with status code 200, with default header values.

returns a healthcheck
*/
type GetHealthCheckOK struct {
	Payload []*models.Hello
}

// IsSuccess returns true when this get health check o k response has a 2xx status code
func (o *GetHealthCheckOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get health check o k response has a 3xx status code
func (o *GetHealthCheckOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get health check o k response has a 4xx status code
func (o *GetHealthCheckOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get health check o k response has a 5xx status code
func (o *GetHealthCheckOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get health check o k response a status code equal to that given
func (o *GetHealthCheckOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetHealthCheckOK) Error() string {
	return fmt.Sprintf("[GET /health][%d] getHealthCheckOK  %+v", 200, o.Payload)
}

func (o *GetHealthCheckOK) String() string {
	return fmt.Sprintf("[GET /health][%d] getHealthCheckOK  %+v", 200, o.Payload)
}

func (o *GetHealthCheckOK) GetPayload() []*models.Hello {
	return o.Payload
}

func (o *GetHealthCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
