// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateProfileReader is a Reader for the CreateProfile structure.
type CreateProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateProfileOK creates a CreateProfileOK with default headers values
func NewCreateProfileOK() *CreateProfileOK {
	return &CreateProfileOK{}
}

/*
CreateProfileOK describes a response with status code 200, with default header values.

create user
*/
type CreateProfileOK struct {
	Payload *CreateProfileOKBody
}

// IsSuccess returns true when this create profile o k response has a 2xx status code
func (o *CreateProfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create profile o k response has a 3xx status code
func (o *CreateProfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create profile o k response has a 4xx status code
func (o *CreateProfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create profile o k response has a 5xx status code
func (o *CreateProfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create profile o k response a status code equal to that given
func (o *CreateProfileOK) IsCode(code int) bool {
	return code == 200
}

func (o *CreateProfileOK) Error() string {
	return fmt.Sprintf("[POST /profile][%d] createProfileOK  %+v", 200, o.Payload)
}

func (o *CreateProfileOK) String() string {
	return fmt.Sprintf("[POST /profile][%d] createProfileOK  %+v", 200, o.Payload)
}

func (o *CreateProfileOK) GetPayload() *CreateProfileOKBody {
	return o.Payload
}

func (o *CreateProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(CreateProfileOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
CreateProfileBody create profile body
swagger:model CreateProfileBody
*/
type CreateProfileBody struct {

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// phone number
	PhoneNumber string `json:"phone_number,omitempty"`
}

// Validate validates this create profile body
func (o *CreateProfileBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create profile body based on context it is used
func (o *CreateProfileBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateProfileBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateProfileBody) UnmarshalBinary(b []byte) error {
	var res CreateProfileBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
CreateProfileOKBody create profile o k body
swagger:model CreateProfileOKBody
*/
type CreateProfileOKBody struct {

	// code
	Code float64 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this create profile o k body
func (o *CreateProfileOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create profile o k body based on context it is used
func (o *CreateProfileOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *CreateProfileOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreateProfileOKBody) UnmarshalBinary(b []byte) error {
	var res CreateProfileOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
