// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCreateProfileParams creates a new CreateProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateProfileParams() *CreateProfileParams {
	return &CreateProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateProfileParamsWithTimeout creates a new CreateProfileParams object
// with the ability to set a timeout on a request.
func NewCreateProfileParamsWithTimeout(timeout time.Duration) *CreateProfileParams {
	return &CreateProfileParams{
		timeout: timeout,
	}
}

// NewCreateProfileParamsWithContext creates a new CreateProfileParams object
// with the ability to set a context for a request.
func NewCreateProfileParamsWithContext(ctx context.Context) *CreateProfileParams {
	return &CreateProfileParams{
		Context: ctx,
	}
}

// NewCreateProfileParamsWithHTTPClient creates a new CreateProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateProfileParamsWithHTTPClient(client *http.Client) *CreateProfileParams {
	return &CreateProfileParams{
		HTTPClient: client,
	}
}

/*
CreateProfileParams contains all the parameters to send to the API endpoint

	for the create profile operation.

	Typically these are written to a http.Request.
*/
type CreateProfileParams struct {

	// Body.
	Body CreateProfileBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateProfileParams) WithDefaults() *CreateProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create profile params
func (o *CreateProfileParams) WithTimeout(timeout time.Duration) *CreateProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create profile params
func (o *CreateProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create profile params
func (o *CreateProfileParams) WithContext(ctx context.Context) *CreateProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create profile params
func (o *CreateProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create profile params
func (o *CreateProfileParams) WithHTTPClient(client *http.Client) *CreateProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create profile params
func (o *CreateProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create profile params
func (o *CreateProfileParams) WithBody(body CreateProfileBody) *CreateProfileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create profile params
func (o *CreateProfileParams) SetBody(body CreateProfileBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
