// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateProfileReader is a Reader for the UpdateProfile structure.
type UpdateProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUpdateProfileOK creates a UpdateProfileOK with default headers values
func NewUpdateProfileOK() *UpdateProfileOK {
	return &UpdateProfileOK{}
}

/*
UpdateProfileOK describes a response with status code 200, with default header values.

create user
*/
type UpdateProfileOK struct {
	Payload *UpdateProfileOKBody
}

// IsSuccess returns true when this update profile o k response has a 2xx status code
func (o *UpdateProfileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update profile o k response has a 3xx status code
func (o *UpdateProfileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update profile o k response has a 4xx status code
func (o *UpdateProfileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update profile o k response has a 5xx status code
func (o *UpdateProfileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update profile o k response a status code equal to that given
func (o *UpdateProfileOK) IsCode(code int) bool {
	return code == 200
}

func (o *UpdateProfileOK) Error() string {
	return fmt.Sprintf("[PUT /profile][%d] updateProfileOK  %+v", 200, o.Payload)
}

func (o *UpdateProfileOK) String() string {
	return fmt.Sprintf("[PUT /profile][%d] updateProfileOK  %+v", 200, o.Payload)
}

func (o *UpdateProfileOK) GetPayload() *UpdateProfileOKBody {
	return o.Payload
}

func (o *UpdateProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(UpdateProfileOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
UpdateProfileBody update profile body
swagger:model UpdateProfileBody
*/
type UpdateProfileBody struct {

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// phone number
	PhoneNumber string `json:"phone_number,omitempty"`
}

// Validate validates this update profile body
func (o *UpdateProfileBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update profile body based on context it is used
func (o *UpdateProfileBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateProfileBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateProfileBody) UnmarshalBinary(b []byte) error {
	var res UpdateProfileBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
UpdateProfileOKBody update profile o k body
swagger:model UpdateProfileOKBody
*/
type UpdateProfileOKBody struct {

	// code
	Code float64 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this update profile o k body
func (o *UpdateProfileOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update profile o k body based on context it is used
func (o *UpdateProfileOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *UpdateProfileOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UpdateProfileOKBody) UnmarshalBinary(b []byte) error {
	var res UpdateProfileOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
